export enum PrimitiveType {
  AR = 'AR',
  AC = 'AC',
  ADC = 'ADC',
  DD = 'DD',
  MD = 'MD',
  NAR = 'NAR',
  CFD = 'CFD',
  FD = 'FD',
  MFD = 'MFD',
  Stats = 'Stats',
  TypoFD = 'TypoFD',
  AFD = 'AFD',
  AFDVerification = 'AFDverification',
}
